name: Complete DevOps Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Build Docker image
        working-directory: ./terraform-configs
        run: |
          docker build -t chineduebinaso/complete-devops-project:${{ env.SHORT_SHA }} .
          
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Push Docker image
        run: |
          docker push chineduebinaso/complete-devops-project:${{ env.SHORT_SHA }}